#!/usr/bin/env bash
# scripts/generate-skills-md.sh
# Auto-generates .agents/SKILLS.md from skill frontmatter.
# Run after adding or modifying a skill in .agents/skills/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="${REPO_ROOT}/.agents/skills"
OUT="${REPO_ROOT}/.agents/SKILLS.md"

cat > "${OUT}" << 'HEADER'
<!-- AUTO-GENERATED by scripts/generate-skills-md.sh — do not edit by hand -->
# Agent Skills Index

Reusable skill runbooks for this Rust template repository.
Run `bash scripts/generate-skills-md.sh` to regenerate after adding or modifying skills.

## Available Skills

| Skill | Path | Description |
|-------|------|-------------|
HEADER

for skill_dir in "${SKILLS_DIR}"/*/; do
  skill_file="${skill_dir}SKILL.md"
  [[ -f "${skill_file}" ]] || continue

  name=$(grep "^name:" "${skill_file}" | head -1 | sed 's/^name:[[:space:]]*//')
  # Handle both inline description and YAML block scalar (>)
  raw_desc=$(grep "^description:" "${skill_file}" | head -1 | sed 's/^description:[[:space:]]*//' | tr -d '"')
  if [[ "${raw_desc}" == ">" || "${raw_desc}" == "|" ]]; then
    desc=$(awk '/^description:/{found=1; next} found && /^[[:space:]]+/{gsub(/^[[:space:]]+/,""); print; exit} found && /^[^[:space:]]/{exit}' "${skill_file}" | cut -c1-100)
  else
    desc=$(echo "${raw_desc}" | cut -c1-100)
  fi
  rel_path="skills/$(basename "${skill_dir}")/SKILL.md"

  printf "| \`%s\` | [%s](%s) | %s |\n" "${name}" "${rel_path}" "${rel_path}" "${desc}" >> "${OUT}"
done

echo "" >> "${OUT}"
echo "Generated $(grep -c "^\| \`" "${OUT}") skills." >&2
echo "✓ ${OUT}"
