#!/usr/bin/env bash
# Generate llms.txt and llms-full.txt
# This provides structured context for AI agents

set -euo pipefail

# Get the repository root directory
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LLMS_FILE="${REPO_ROOT}/llms.txt"
FULL_FILE="${REPO_ROOT}/llms-full.txt"

echo "Generating llms.txt and llms-full.txt..."
echo "Repository root: ${REPO_ROOT}"

# 1. Generate llms.txt (Condensed overview)
# Use a template for the token-efficient project overview
cat > "${LLMS_FILE}" << EOF
# Rust 2026 Template

> A production-ready Rust workspace template with modern tooling, CI/CD, and AI agent integration.
>
> This file is auto-generated. For complete source context, see llms-full.txt.
> Version: $(cat "${REPO_ROOT}/VERSION")

## Project Overview

This is a comprehensive Rust workspace template designed for 2026 best practices. It includes a multi-crate workspace structure, integrated testing with nextest, and specialized AI agent support.

## Documentation Map

- **README.md**: Human-first project overview and feature set.
- **QUICKSTART.md**: Step-by-step setup and developer onboarding.
- **AGENTS.md**: Canonical rules and instructions for coding agents.
- **.agents/skills/**: Executable task knowledge and workflows.
- **.agents/context/**: Cross-repo context for derived repositories.
- **llms.txt**: Token-efficient project context (this file).

## Architecture

\`\`\`
rust-2026-template/
├── .agents/skills/          # AI agent skill definitions
├── .cargo/config.toml       # Cargo linker + profile config
├── .github/workflows/       # CI/CD GitHub Actions
├── scripts/                 # Development and quality scripts
├── crates/                  # Workspace member crates
├── AGENTS.md                # Canonical AI agent guidance
├── Cargo.toml               # Workspace manifest
└── README.md                # Project documentation
\`\`\`

## Key Files

### Configuration & Health
- \`Cargo.toml\`: Workspace manifest
- \`rust-toolchain.toml\`: Pinned toolchain (1.88+)
- \`ci-summary.md\`: Current CI health status (in .agents/ci/)
- \`deny.toml\`: Security and license policy

### Cross-Repo Context
- \`.agents/context/external-repos.json\`: Linked repositories and their agent context
- \`.agents/context/shared-conventions.md\`: Conventions that apply across all derived repos

### AI Agent Skills
- \`build-rust\`, \`lint-rust\`, \`test-rust\`, \`release-rust\`
- \`anti-ai-slop\`, \`privacy-first\`, \`crates-io-name-check\`

## Development Commands

- \`cargo build --workspace\`: Build all crates
- \`./scripts/code-quality.sh check\`: Run all quality checks
- \`cargo nextest run --workspace\`: Run all tests
- \`./scripts/quality-gates.sh\`: Run all quality gates

## Code Conventions

- **File Size**: Max 500 LOC per source file
- **Lints**: Zero clippy warnings allowed (pedantic set)
- **Safety**: \`#![forbid(unsafe_code)]\` enforced
- **Error Handling**: \`thiserror\` (libs), \`anyhow\` (bins)
- **Documentation**: Public items require \`///\` comments
EOF

# 2. Generate llms-full.txt (Concatenated context)
# Files to concatenate (in order)
FILES=(
    "llms.txt"
    "README.md"
    "AGENTS.md"
    "CONTRIBUTING.md"
    "QUICKSTART.md"
    "SECURITY.md"
)

# Clear or create the output file
: > "${FULL_FILE}"

# Add header
cat >> "${FULL_FILE}" << EOF
# Rust 2026 Template - Full LLM Context

> This file is auto-generated by scripts/generate-llms-txt.sh
> Version: $(cat "${REPO_ROOT}/VERSION")

This comprehensive context file combines all key documentation for AI agents.

================================================================================

EOF

# Concatenate each file with separators
for file in "${FILES[@]}"; do
    file_path="${REPO_ROOT}/${file}"
    
    if [[ -f "${file_path}" ]]; then
        echo "Adding to full context: ${file}"
        
        # Add file separator
        cat >> "${FULL_FILE}" << EOF

================================================================================
# Source: ${file}
================================================================================

EOF
        
        # Append file content
        cat "${file_path}" >> "${FULL_FILE}"
        
        # Add spacing
        echo "" >> "${FULL_FILE}"
        echo "" >> "${FULL_FILE}"
    else
        echo "Warning: ${file} not found, skipping..."
    fi
done

# Add footer
cat >> "${FULL_FILE}" << 'EOF'

================================================================================
# End of llms-full.txt
================================================================================
EOF

echo "✓ Successfully generated: ${LLMS_FILE}"
echo "✓ Successfully generated: ${FULL_FILE}"
echo "Full context size: $(wc -c < "${FULL_FILE}") bytes"
