#!/usr/bin/env bash
# Generate llms-full.txt by concatenating key documentation files
# This provides a comprehensive context file for AI agents

set -euo pipefail

# Get the repository root directory
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/llms-full.txt"

# Files to concatenate (in order)
FILES=(
    "llms.txt"
    "README.md"
    "AGENTS.md"
    "CONTRIBUTING.md"
    "QUICKSTART.md"
    "SECURITY.md"
)

echo "Generating llms-full.txt..."
echo "Repository root: ${REPO_ROOT}"

# Clear or create the output file
: > "${OUTPUT_FILE}"

# Add header
cat >> "${OUTPUT_FILE}" << 'EOF'
# Rust 2026 Template - Full LLM Context

> This file is auto-generated by scripts/generate-llms-txt.sh
> Last generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

This comprehensive context file combines all key documentation for AI agents.

================================================================================

EOF

# Concatenate each file with separators
for file in "${FILES[@]}"; do
    file_path="${REPO_ROOT}/${file}"
    
    if [[ -f "${file_path}" ]]; then
        echo "Adding: ${file}"
        
        # Add file separator
        cat >> "${OUTPUT_FILE}" << EOF

================================================================================
# Source: ${file}
================================================================================

EOF
        
        # Append file content
        cat "${file_path}" >> "${OUTPUT_FILE}"
        
        # Add spacing
        echo "" >> "${OUTPUT_FILE}"
        echo "" >> "${OUTPUT_FILE}"
    else
        echo "Warning: ${file} not found, skipping..."
    fi
done

# Add footer
cat >> "${OUTPUT_FILE}" << 'EOF'

================================================================================
# End of llms-full.txt
================================================================================
EOF

echo "✓ Successfully generated: ${OUTPUT_FILE}"
echo "File size: $(wc -c < "${OUTPUT_FILE}") bytes"
echo "Line count: $(wc -l < "${OUTPUT_FILE}") lines"
