name: Secret Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.4.4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d51132893f554582c8a24c54573b18caed57c06 # v4.2.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run secretlint
        run: npx secretlint "**/*"
